# @package _global_

robot:
  type: single_integrator
  radius: 0.3
  vmax: 1.5
  amax: 2.0
  omega_max: 1.5707963267948966
  ini_goal_dist: 8.0

env:
  reward:
    potential_factor: 2.0
    back_factor: 0.0
    spin_factor: 0.0
